sources:
  - Inconsolata.glyphs
axisOrder:
  - wdth
  - wght
familyName: Inconsolata
buildStatic: false
flattenComponents: false
decomposeTransformedComponents: true
vttSources:
  Inconsolata[wdth,wght].ttf: vtt_hinting.ttx
includeSourceFixes: true